name: build

on:
  push:
    branches: [ "develop-pure" ]
  pull_request:
    branches: [ "develop-pure" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_tag:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      build_tag: ${{ steps.tag_step.outputs.build_tag }}
    steps:
      - name: Checkout pull-request
        uses: actions/checkout@v4

      - name: Get build tag
        id: tag_step
        run: |
          build_tag=$(date +%Y-%m-%d)_$(git rev-parse --short HEAD)
          echo "build_tag=$build_tag" >> "$GITHUB_OUTPUT"

  build_debian_12_armhf:
    needs: build_tag
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    outputs:
      build_tag: ${{ steps.tag_step.outputs.build_tag }}
    steps:
      - name: Checkout pull-request
        uses: actions/checkout@v4

      - name: Generate Installers
        run: |
          rm -rf output
          ./runme.sh debian_12_armhf

      - name: Publish to S3
        if: github.ref == 'refs/heads/develop-pure' && github.event_name != 'pull_request'
        uses: shallwefootball/upload-s3-action@v1.3.3
        with:
          aws_key_id: ${{ secrets.IMAGES_S3_ACCESS }}
          aws_secret_access_key: ${{ secrets.IMAGES_S3_SECRET }}
          aws_bucket: ${{ secrets.IMAGES_S3_BUCKET }}
          endpoint: ${{ secrets.IMAGES_S3_HOST }}
          source_dir: output
          destination_dir: Pure-Debian/armhf/12/${{ needs.build_tag.outputs.build_tag }}
